QoL changes
Mester-Ulquiorra/web pull request #10
Opened 2023-08-12 15:02 UTC by MesterMan03

+ Alerts from ws are now saved.
+ Toast text is nicer.
~ Appeal button doesn't show up if the punishment is appealed.
~ Better TypeScript compatibility.
~ Changed toast text timings for better readability.

2023-08-12 16:41 UTC, noClaps requested changes
I think it would be better to have all of the alerts code in a single `alerts.ts` file, while keeping the `types.ts` only for types. As we expand alerts functionality, we can split the code into more files and put it all into an `alerts/` directory.

2023-08-12 16:56 UTC, noClaps commented on src/scripts/types.ts
>  }
I think this function is pointless, since this check can easily be made inline.

2023-08-12 16:56 UTC, noClaps commented on src/pages/alerts.astro
> +      alertElement.innerHTML = alert.data.reason;
You can use:

```ts
alertElement.classList.add(alert.data.status)
```

to achieve this. If you want the different alert types to be styled differently then you have to modify the element itself in some way for the CSS to pick it up and style it, whether that's using HTML datasets, or classes.

2023-08-12 16:58 UTC, MesterMan03 commented
> I think this function is pointless, since this check can easily be made inline. 

it is pointless *for now*, but when we add more alert types, we'll have to add it anyway

2023-08-12 16:59 UTC, noClaps commented
You also haven't added the `appealed` prop to the main `pages/punishments.astro` page.

2023-08-12 17:01 UTC, noClaps commented
> > I think this function is pointless, since this check can easily be made inline.
> 
> it is pointless _for now_, but when we add more alert types, we'll have to add it anyway

Yes, but if those are also `return alert.type === [alert type]` then that's still a check that can be made inline.

2023-08-13 13:56 UTC, noClaps approved these changes

2023-08-13 13:57 UTC, noClaps commented
LGTM

2023-08-13 13:57 UTC, merged